// Sri Lanka Crop-Specific Recommendations
// Sources:
//   - Department of Agriculture, Sri Lanka (https://doa.gov.lk)
//   - Rice Research & Development Institute (https://doa.gov.lk/rrdi)
//   - Coconut Research Institute (https://cri.gov.lk)
//   - Tea Research Institute (https://tri.lk)
//   - Export Agriculture Dept. (https://dea.gov.lk)
//   - FAO Sri Lanka (https://www.fao.org/srilanka)

export const CROP_RECOMMENDATIONS = [
    {
        id: 'rice',
        name: 'Rice (Paddy)',
        sinhalaName: 'වී / හාල්',
        tamilName: 'நெல்',
        emoji: '🌾',
        zones: ['wet', 'dry', 'intermediate'],
        seasons: ['yala', 'maha'],
        overview: 'Rice is Sri Lanka\'s staple food crop, cultivated on over 700,000 hectares. It is grown island-wide in both Yala (Apr–Aug) and Maha (Oct–Feb) seasons. The dry zone produces over 60% of paddy, heavily relying on major irrigation schemes like Mahaweli.',
        economicImportance: 'Provides livelihood for ~1.8 million farming families. Annual production ~4.5 million metric tons.',
        varieties: [
            { name: 'Bg 352', type: 'Improved', duration: '3 months', yield: '6-7 t/ha', pericarp: 'White', notes: 'Widely grown, good for both seasons' },
            { name: 'Bg 300', type: 'Improved', duration: '3 months', yield: '5-6 t/ha', pericarp: 'White', notes: 'Popular in dry zone irrigated areas' },
            { name: 'At 362', type: 'Improved', duration: '3.5 months', yield: '7-8 t/ha', pericarp: 'Red', notes: 'High yielding, suitable island-wide' },
            { name: 'At 313', type: 'Improved', duration: '3 months', yield: '9.5 t/ha', pericarp: 'White', notes: 'Highest yield potential, DOA recommended' },
            { name: 'Suwandel', type: 'Traditional', duration: '4 months', yield: '2-3 t/ha', pericarp: 'White', notes: 'Premium aromatic variety, high market value' },
            { name: 'Kalu Heenati', type: 'Traditional', duration: '4 months', yield: '2-3 t/ha', pericarp: 'Red', notes: 'Nutrient-rich traditional variety' },
        ],
        soilRequirements: { pH: '5.0 - 6.5', type: 'Heavy clay to clay loam', drainage: 'Impeded drainage preferred (holds standing water)', preparation: 'Wet land preparation: plough, puddle, and level. Two ploughings recommended.' },
        waterRequirements: 'Standing water of 5-7.5 cm during vegetative stage. Reduce water 2 weeks before harvest. Total water need: 1200-1800mm per season.',
        plantingGuide: { spacing: '15×15 cm or 20×15 cm', method: 'Transplanting or broadcast sowing', depth: '2-3 cm', seedRate: '100-120 kg/ha (broadcast), 40-50 kg/ha (transplanting)', bestMonths: { yala: 'April', maha: 'October' } },
        growthStages: [
            { stage: 'Seedling', duration: '0-21 days', care: 'Maintain 2-3cm water level. Apply basal fertilizer before transplanting.' },
            { stage: 'Vegetative/Tillering', duration: '21-50 days', care: 'Maintain 5cm water. Apply 1st top dressing at 2 weeks, 2nd at 5 weeks after planting.' },
            { stage: 'Reproductive', duration: '50-80 days', care: 'Maintain 5-7cm water during flowering. Watch for brown planthopper and blast disease.' },
            { stage: 'Ripening', duration: '80-100 days', care: 'Drain water gradually 2 weeks before harvest. Monitor for grain discoloration.' },
        ],
        harvestingTips: 'Harvest when 80% of grains turn golden. Use sickle or combine harvester. Dry paddy to 12-14% moisture for storage. Thresh within 24 hours of cutting.',
        marketInfo: { peakDemand: 'Year-round staple', avgPrice: 'Rs. 80-120/kg (milled rice)', exportPotential: 'Limited - mostly for domestic consumption' },
    },
    {
        id: 'tea',
        name: 'Tea',
        sinhalaName: 'තේ',
        tamilName: 'தேயிலை',
        emoji: '🍵',
        zones: ['wet'],
        seasons: ['yala', 'maha'],
        overview: 'Ceylon Tea is world-renowned for quality. Grown primarily in the central highlands and wet zone. Sri Lanka is the 4th largest tea producer globally. Classified by elevation: Low-grown (<600m), Mid-grown (600-1200m), High-grown (>1200m).',
        economicImportance: 'Employs over 1 million workers. Major export earner contributing ~$1.3 billion annually.',
        varieties: [
            { name: 'TRI 2025', type: 'Cultivar', duration: 'Perennial', yield: '2500-3000 kg/ha/yr', pericarp: '-', notes: 'High yielding, good for low-country' },
            { name: 'TRI 2026', type: 'Cultivar', duration: 'Perennial', yield: '2000-2500 kg/ha/yr', pericarp: '-', notes: 'Quality cultivar for mid-country' },
            { name: 'TRI 4049', type: 'Cultivar', duration: 'Perennial', yield: '2500 kg/ha/yr', pericarp: '-', notes: 'Drought tolerant, good for intermediate areas' },
            { name: 'DT 1', type: 'Cultivar', duration: 'Perennial', yield: '2200 kg/ha/yr', pericarp: '-', notes: 'Recommended for Nuwara Eliya district' },
        ],
        soilRequirements: { pH: '4.5 - 5.5', type: 'Red-Yellow Podzolic, well-drained loamy soil', drainage: 'Good drainage essential, waterlogging fatal', preparation: 'Deep ploughing to 60cm. Add compost at 10 t/ha. Ensure contour planting on slopes.' },
        waterRequirements: 'Annual rainfall >1500mm well-distributed. No irrigation needed in wet zone. Drought for >6 weeks reduces yield significantly.',
        plantingGuide: { spacing: '0.6m × 1.2m (single row) or 0.6m × 0.6m × 1.5m (hedge-row)', method: 'Vegetatively propagated cuttings', depth: 'Plant at collar level', seedRate: '13,000-15,000 plants/ha', bestMonths: { yala: 'May-June', maha: 'October-November' } },
        growthStages: [
            { stage: 'Nursery', duration: '6-12 months', care: 'Maintain 20-25% shade. Regular misting. Apply NPK fertilizer monthly.' },
            { stage: 'Young Tea', duration: '1-3 years', care: 'Establish shade trees. Formative pruning at 6-month intervals. No plucking until 3 years.' },
            { stage: 'Mature/Bearing', duration: '3+ years', care: 'Regular plucking every 7-10 days. Prune every 3-5 years. Apply fertilizer 3 times/year.' },
        ],
        harvestingTips: 'Pluck two leaves and a bud. Pluck every 7-10 days during flush periods. Avoid plucking during heavy rain. Deliver to factory within 6 hours.',
        marketInfo: { peakDemand: 'Year-round, premium prices July-September', avgPrice: 'Rs. 400-1200/kg (made tea, varies by grade)', exportPotential: 'High - major export commodity' },
    },
    {
        id: 'rubber',
        name: 'Rubber',
        sinhalaName: 'රබර්',
        tamilName: 'ரப்பர்',
        emoji: '🌳',
        zones: ['wet'],
        seasons: ['yala', 'maha'],
        overview: 'Rubber is a key plantation crop in Sri Lanka\'s low-country wet zone. Grown primarily in Kalutara, Ratnapura, Kegalle, and Galle districts. Latex is tapped from mature trees for natural rubber production.',
        economicImportance: 'Cultivated on ~130,000 hectares. Annual production ~80,000 MT. Provides employment to ~300,000 workers.',
        varieties: [
            { name: 'RRIC 100', type: 'Clone', duration: '6 years to tap', yield: '1800 kg/ha/yr', pericarp: '-', notes: 'Most popular clone, high yielding' },
            { name: 'RRIC 121', type: 'Clone', duration: '5.5 years to tap', yield: '2000 kg/ha/yr', pericarp: '-', notes: 'Early maturing, wind resistant' },
            { name: 'RRIC 130', type: 'Clone', duration: '6 years to tap', yield: '1900 kg/ha/yr', pericarp: '-', notes: 'Good for marginal areas' },
        ],
        soilRequirements: { pH: '4.0 - 6.0', type: 'Red-Yellow Podzolic, lateritic soils', drainage: 'Well-drained, deep soils >1.5m', preparation: 'Clear, terrace on slopes, plant cover crops (Pueraria, Mucuna) between rows.' },
        waterRequirements: 'Annual rainfall >2000mm. No irrigation. Tapping suspended during heavy rain and wintering period (Jan-Feb).',
        plantingGuide: { spacing: '8.1m × 2.4m or 6.7m × 3.3m', method: 'Bud-grafted stumps or polybag plants', depth: 'Plant at union level', seedRate: '500-600 trees/ha', bestMonths: { yala: 'May-June', maha: 'October-November' } },
        growthStages: [
            { stage: 'Immature', duration: '0-6 years', care: 'Maintain cover crops. Apply fertilizer twice yearly. Prune lower branches.' },
            { stage: 'Tapping', duration: '6-30 years', care: 'Tap on alternate days using half-spiral cut. Apply stimulants as recommended by RRISL.' },
        ],
        harvestingTips: 'Begin tapping when trunk girth reaches 50cm at 120cm height. Tap early morning (5-7 AM). Use S/2 d2 tapping system. Collect latex within 3 hours.',
        marketInfo: { peakDemand: 'Year-round with global price fluctuations', avgPrice: 'Rs. 250-450/kg (crepe rubber)', exportPotential: 'Moderate - used domestically and exported' },
    },
    {
        id: 'cinnamon',
        name: 'Cinnamon',
        sinhalaName: 'කුරුඳු',
        tamilName: 'இலவங்கப்பட்டை',
        emoji: '🪵',
        zones: ['wet'],
        seasons: ['yala', 'maha'],
        overview: 'Sri Lanka produces 90% of the world\'s true cinnamon (Cinnamomum verum). Grown primarily in the southern wet zone coastal belt from Negombo to Matara. Galle and Matara districts are the largest producers.',
        economicImportance: 'Cultivated on ~35,000 hectares. Major export earner ~$350 million/year. Provides employment to thousands in processing.',
        varieties: [
            { name: 'Sri Gemunu', type: 'Improved', duration: '2-3 years to first harvest', yield: '2500 kg/ha/yr (quills)', pericarp: '-', notes: 'DOA recommended, high bark quality' },
            { name: 'Sri Wijaya', type: 'Improved', duration: '2-3 years to first harvest', yield: '2200 kg/ha/yr', pericarp: '-', notes: 'High oil content, good for essential oil extraction' },
            { name: 'Local selections', type: 'Traditional', duration: '3 years to first harvest', yield: '1500-2000 kg/ha', pericarp: '-', notes: 'Widely cultivated across southern districts' },
        ],
        soilRequirements: { pH: '5.5 - 6.5', type: 'Sandy loam, well-drained lateritic soils', drainage: 'Excellent drainage essential, no waterlogging', preparation: 'Clear land, dig pits 30×30×30cm. Add compost/cow dung to each pit.' },
        waterRequirements: 'Annual rainfall >1875mm. Grows well with 1700-3500mm. Relative humidity 75-85% optimal.',
        plantingGuide: { spacing: '1.5m × 1.5m to 3m × 3m', method: 'Seeds or vegetative propagation', depth: '30cm pits', seedRate: '1100-4400 plants/ha depending on spacing', bestMonths: { yala: 'May-June', maha: 'October-November' } },
        growthStages: [
            { stage: 'Establishment', duration: '0-2 years', care: 'Mulch around plants. Water during dry spells. Apply organic fertilizer.' },
            { stage: 'First Harvest', duration: '2-3 years', care: 'Cut stems at 45° angle, 2 inches above ground. Harvest when bark turns brown.' },
            { stage: 'Regular Production', duration: '3+ years', care: 'Harvest twice per year after monsoons. Manage 5-6 shoots per stool.' },
        ],
        harvestingTips: 'Harvest when shoots are ~3cm diameter and bark is brown. Cut at 45° angle. Peel within same day. Scrape outer bark, rub with brass rod to loosen inner bark.',
        marketInfo: { peakDemand: 'Year-round export demand, peak Nov-Feb', avgPrice: 'Rs. 2000-5000/kg (quills, varies by grade)', exportPotential: 'Very High - world\'s premium cinnamon source' },
    },
    {
        id: 'pepper',
        name: 'Black Pepper',
        sinhalaName: 'ගම්මිරිස්',
        tamilName: 'மிளகு',
        emoji: '🫑',
        zones: ['wet', 'intermediate'],
        seasons: ['yala', 'maha'],
        overview: 'Black pepper, the "King of Spices", is grown as a climbing vine on support trees in the mid-country wet and intermediate zones. Kandy, Matale, Kegalle, and Ratnapura are major producing districts.',
        economicImportance: 'Cultivated on ~35,000 hectares. Important export spice contributing ~$100 million annually.',
        varieties: [
            { name: 'Panniyur 1', type: 'Improved', duration: '3 years to fruit', yield: '2.5 kg/vine', pericarp: '-', notes: 'Most popular, high yielding' },
            { name: 'Kurunegala Selection', type: 'Local', duration: '3 years to fruit', yield: '2.0 kg/vine', pericarp: '-', notes: 'Hardy local selection, disease tolerant' },
            { name: 'Dindigul', type: 'Improved', duration: '3 years to fruit', yield: '2.2 kg/vine', pericarp: '-', notes: 'Good quality berries' },
        ],
        soilRequirements: { pH: '5.5 - 6.5', type: 'Well-drained loamy soil rich in organic matter', drainage: 'Good drainage essential', preparation: 'Dig pits 50×50×50cm near support trees. Add 5kg compost per pit.' },
        waterRequirements: 'Annual rainfall 1500-3000mm. Irrigation during dry spells. Mulching helps conserve moisture.',
        plantingGuide: { spacing: '2.5m × 2.5m to 3m × 3m (depends on support tree spacing)', method: 'Rooted cuttings planted at base of support trees', depth: '50cm pits', seedRate: '1100-1600 vines/ha', bestMonths: { yala: 'May-June', maha: 'October' } },
        growthStages: [
            { stage: 'Establishment', duration: '0-3 years', care: 'Train vines on support trees. Apply organic fertilizer. Mulch base of vines.' },
            { stage: 'Bearing', duration: '3+ years', care: 'Apply NPK fertilizer 3 times/year. Prune support tree to regulate shade. Watch for Phytophthora foot rot.' },
        ],
        harvestingTips: 'Harvest when 1-2 berries on spike turn red. Pick entire spikes. Dry in sun for 5-7 days until wrinkled and black.',
        marketInfo: { peakDemand: 'Dec-Feb harvest season, year-round demand', avgPrice: 'Rs. 1500-3000/kg', exportPotential: 'High - global demand for Ceylon pepper' },
    },
    {
        id: 'coconut',
        name: 'Coconut',
        sinhalaName: 'පොල්',
        tamilName: 'தேங்காய்',
        emoji: '🥥',
        zones: ['wet', 'intermediate', 'dry'],
        seasons: ['yala', 'maha'],
        overview: 'Coconut is the most widely cultivated crop in Sri Lanka, covering ~395,000 hectares. The "Coconut Triangle" (Kurunegala, Puttalam, Gampaha) is the main growing area. Used for copra, desiccated coconut, coconut oil, and fresh consumption.',
        economicImportance: 'Provides livelihood for ~500,000 families. Contributes ~$500 million to export earnings. Multiple value-added products.',
        varieties: [
            { name: 'Sri Lanka Tall (Typica)', type: 'Tall', duration: '5-6 years to fruit', yield: '60-80 nuts/palm/yr', pericarp: '-', notes: 'Most commonly grown variety' },
            { name: 'CRISL 98', type: 'Hybrid', duration: '4 years to fruit', yield: '100-120 nuts/palm/yr', pericarp: '-', notes: 'CRI hybrid, best for wet and wet-intermediate zones' },
            { name: 'CRIC 60', type: 'Dwarf', duration: '3 years to fruit', yield: '80-100 nuts/palm/yr', pericarp: '-', notes: 'Early bearing, suitable for home gardens' },
            { name: 'CRISL 2020 (T×MRD)', type: 'Hybrid', duration: '4 years to fruit', yield: '120+ nuts/palm/yr', pericarp: '-', notes: 'Latest CRI hybrid, highest yield potential' },
        ],
        soilRequirements: { pH: '5.0 - 8.0', type: 'Laterite, coastal sandy, alluvial soils', drainage: 'Good drainage with water-holding capacity', preparation: 'Dig pits 1m×1m×1m (loamy) or 1.2m×1.2m×1.2m (lateritic). Place coconut husks at bottom.' },
        waterRequirements: 'Annual rainfall 1300-2300mm well-distributed. Irrigation beneficial in dry zone during drought. Mulching reduces moisture loss by 30%.',
        plantingGuide: { spacing: '7.5m × 7.5m (triangular) or 8m × 8m (square)', method: 'Selected seedlings or hybrid seedlings from CRI', depth: '1m pits with husk-compost base', seedRate: '160-178 palms/ha', bestMonths: { yala: 'May-June', maha: 'October-November' } },
        growthStages: [
            { stage: 'Nursery', duration: '8-12 months', care: 'Select seed nuts from high-yielding palms. Maintain moisture. Apply fertilizer quarterly.' },
            { stage: 'Young palms', duration: '1-5 years', care: 'Maintain weed-free circle of 1.8m radius. Apply 1/3 adult dose fertilizer increasing yearly. Protect from pests.' },
            { stage: 'Bearing palms', duration: '5+ years', care: 'Apply CRI Adult Palm Mixture (APM) annually. Harvest every 45-60 days.' },
        ],
        harvestingTips: 'Harvest every 45-60 days when nuts are 11-12 months old (brown husk). Climb or use harvesting poles. Store in shade.',
        marketInfo: { peakDemand: 'Year-round, price peaks during festive seasons (April, December)', avgPrice: 'Rs. 50-90/nut, Rs. 350-500/L (coconut oil)', exportPotential: 'High - desiccated coconut, coconut cream, virgin coconut oil' },
    },
    {
        id: 'chili',
        name: 'Chili',
        sinhalaName: 'මිරිස්',
        tamilName: 'மிளகாய்',
        emoji: '🌶️',
        zones: ['dry', 'intermediate'],
        seasons: ['yala', 'maha'],
        overview: 'Chili is a major cash crop cultivated mainly in the dry zone. About 13,000 hectares are planted in the Maha season as rain-fed upland crops. Major growing districts: Anuradhapura, Monaragala, Ampara, Kurunegala.',
        economicImportance: 'Essential in Sri Lankan cuisine. Annual domestic demand ~50,000 MT. Significant import substitution crop.',
        varieties: [
            { name: 'MI-2', type: 'OPV', duration: '120 days', yield: '12-15 t/ha (green)', pericarp: '-', notes: 'Most widely cultivated, versatile for drying and powder' },
            { name: 'KA-2', type: 'OPV', duration: '120 days', yield: '12-14 t/ha', pericarp: '-', notes: 'Good color quality, tolerant to Leaf Curl Complex' },
            { name: 'MI-Hot', type: 'OPV', duration: '110 days', yield: '10-12 t/ha', pericarp: '-', notes: 'High pungency, for curries and chili paste' },
            { name: 'MICH HY1', type: 'Hybrid', duration: '110 days', yield: '32 t/ha (green)', pericarp: '-', notes: 'First local hybrid, highest yield potential' },
            { name: 'Arunalu', type: 'OPV', duration: '115 days', yield: '10-12 t/ha', pericarp: '-', notes: 'Good for dry chili production' },
        ],
        soilRequirements: { pH: '6.0 - 7.0', type: 'Well-drained sandy loam to loam', drainage: 'Good drainage essential, raised beds in heavy soils', preparation: 'Plough and harrow twice. Prepare raised beds 1m wide. Apply 10t/ha compost as basal.' },
        waterRequirements: 'Need 600-1200mm during crop period. Irrigate every 4-5 days initially, weekly during fruiting. Avoid waterlogging.',
        plantingGuide: { spacing: '60×45 cm or 75×30 cm', method: 'Transplanting from nursery at 4-5 weeks', depth: 'Transplant at same depth as nursery', seedRate: '250-350g seed/ha (nursery)', bestMonths: { yala: 'April-May', maha: 'September-October' } },
        growthStages: [
            { stage: 'Nursery', duration: '0-30 days', care: 'Sow in raised beds under partial shade. Treat seeds with Thiamethoxam. Harden off before transplanting.' },
            { stage: 'Vegetative', duration: '30-60 days', care: 'Apply mulch (straw or Gliricidia leaves). Wind breaks of maize/finger millet help reduce pest pressure.' },
            { stage: 'Flowering/Fruiting', duration: '60-120 days', care: 'Switch to high-K fertilizer. Monitor for thrips and mites. Apply Neem extract preventively.' },
        ],
        harvestingTips: 'Pick green chili at full size for fresh market. For dry chili, leave on plant until red. Sun-dry for 7-10 days. Store in dry, ventilated area.',
        marketInfo: { peakDemand: 'Year-round, prices peak April-June', avgPrice: 'Rs. 300-800/kg (green), Rs. 1200-2500/kg (dried)', exportPotential: 'Moderate - mainly domestic consumption' },
    },
    {
        id: 'onion',
        name: 'Big Onion',
        sinhalaName: 'ලොකු ළූණු',
        tamilName: 'பெரிய வெங்காயம்',
        emoji: '🧅',
        zones: ['dry'],
        seasons: ['yala'],
        overview: 'Big onion is cultivated mainly in Jaffna, Matale, and Anuradhapura districts. It requires dry conditions for bulb development. Sri Lanka imports ~200,000 MT annually to meet demand.',
        economicImportance: 'High import substitution potential. Domestic production ~100,000 MT against demand of ~300,000 MT.',
        varieties: [
            { name: 'Dambulla Selection', type: 'Local', duration: '100 days', yield: '15-20 t/ha', pericarp: '-', notes: 'Adapted to Matale/Dambulla area' },
            { name: 'Galewela Light Red', type: 'Local', duration: '90 days', yield: '12-15 t/ha', pericarp: '-', notes: 'Popular in Kurunegala district' },
            { name: 'Rampur', type: 'Improved', duration: '95 days', yield: '18-22 t/ha', pericarp: '-', notes: 'High yielding, good storage quality' },
        ],
        soilRequirements: { pH: '6.0 - 7.0', type: 'Sandy loam to loam, well-drained', drainage: 'Excellent drainage required', preparation: 'Fine tilth needed. Prepare raised beds 1.2m wide, 15cm high. Apply 10-15 t/ha well-decomposed compost.' },
        waterRequirements: 'Irrigate every 3-4 days. Stop irrigation 2 weeks before harvest for bulb curing. Total water need: 500-600mm.',
        plantingGuide: { spacing: '20×10 cm', method: 'Transplanting seedlings at 6-8 weeks', depth: '1-2 cm (seedling base at soil level)', seedRate: '4-5 kg seed/ha', bestMonths: { yala: 'April-May', maha: 'Not recommended' } },
        growthStages: [
            { stage: 'Seedling', duration: '0-45 days', care: 'Nursery in raised beds under partial shade. Transplant when 15cm tall.' },
            { stage: 'Vegetative', duration: '45-70 days', care: 'Irrigate regularly. Apply fertilizer at 2 and 4 weeks after transplanting. Weed regularly.' },
            { stage: 'Bulb Formation', duration: '70-100 days', care: 'Reduce watering. Apply potassium. Stop nitrogen. Watch for purple blotch disease.' },
        ],
        harvestingTips: 'Harvest when 50-75% of tops fall over naturally. Cure in shade for 7-10 days. Store in well-ventilated area. Properly cured onions store for 3-4 months.',
        marketInfo: { peakDemand: 'Year-round, prices peak Aug-Nov', avgPrice: 'Rs. 150-400/kg', exportPotential: 'Low - mostly domestic consumption' },
    },
    {
        id: 'maize',
        name: 'Maize (Corn)',
        sinhalaName: 'බඩ ඉරිඟු',
        tamilName: 'சோளம்',
        emoji: '🌽',
        zones: ['dry', 'intermediate'],
        seasons: ['yala', 'maha'],
        overview: 'Maize is the second most important cereal after rice. Grown as rainfed crop in dry and intermediate zones. Major production in Anuradhapura, Monaragala, Badulla, and Kurunegala districts. Used for animal feed, poultry industry, and human consumption.',
        economicImportance: 'Cultivated on ~60,000 hectares. Important for the poultry feed industry. Import substitution crop.',
        varieties: [
            { name: 'Ruwan', type: 'OPV', duration: '90-100 days', yield: '4-5 t/ha', pericarp: '-', notes: 'DOA recommended OPV, widely grown' },
            { name: 'Bhadra', type: 'OPV', duration: '100-110 days', yield: '4.5-5.5 t/ha', pericarp: '-', notes: 'Good for intermediate zone' },
            { name: 'Pacific 984', type: 'Hybrid', duration: '110-120 days', yield: '8-10 t/ha', pericarp: '-', notes: 'Popular hybrid, highest yield' },
            { name: 'Sampath', type: 'OPV', duration: '95 days', yield: '4-5 t/ha', pericarp: '-', notes: 'Short duration, suitable for late planting' },
        ],
        soilRequirements: { pH: '5.5 - 7.0', type: 'Sandy loam to loam', drainage: 'Well-drained essential', preparation: 'Plough and harrow twice. Apply 5t/ha compost. Prepare rows 75cm apart.' },
        waterRequirements: 'Rainfall 500-800mm during crop period. Critical water need at tasseling and grain filling stages. Irrigate if dry spell >7 days during flowering.',
        plantingGuide: { spacing: '60×25 cm or 75×25 cm', method: 'Direct seeding', depth: '3-5 cm', seedRate: '20-25 kg/ha (OPV), 15-18 kg/ha (hybrid)', bestMonths: { yala: 'April', maha: 'October' } },
        growthStages: [
            { stage: 'Emergence', duration: '0-14 days', care: 'Ensure good soil moisture for germination. Gap fill at 7-10 days.' },
            { stage: 'Vegetative', duration: '14-50 days', care: 'Apply 1st top dressing at 3 weeks. Weed control critical first 30 days. Earth up at 4 weeks.' },
            { stage: 'Tasseling/Silking', duration: '50-70 days', care: 'Critical water stage. Apply 2nd top dressing. Watch for stem borer and fall armyworm.' },
            { stage: 'Grain Filling', duration: '70-100 days', care: 'Maintain moisture. Monitor for ear rot. Harvest when kernels are hard and glossy.' },
        ],
        harvestingTips: 'Harvest when husks are dry and kernels hard (20-22% moisture). Sun-dry cobs for 3-5 days. Shell and clean. Store at <13% moisture.',
        marketInfo: { peakDemand: 'Year-round demand from poultry industry', avgPrice: 'Rs. 60-100/kg', exportPotential: 'Low - mainly domestic animal feed use' },
    },
    {
        id: 'groundnut',
        name: 'Groundnut',
        sinhalaName: 'රටකජු',
        tamilName: 'நிலக்கடலை',
        emoji: '🥜',
        zones: ['dry', 'intermediate'],
        seasons: ['yala'],
        overview: 'Groundnut is an important oilseed and food crop grown as a rainfed crop in dry and intermediate zones. Major production in Kurunegala, Hambantota, Puttalam, and Anuradhapura districts.',
        economicImportance: 'Important source of protein and oil for rural communities. Growing demand for groundnut-based snack industry.',
        varieties: [
            { name: 'Tissa', type: 'Improved', duration: '105 days', yield: '2.5-3 t/ha', pericarp: '-', notes: 'DOA recommended, widely adapted' },
            { name: 'Indi', type: 'Improved', duration: '100 days', yield: '2-2.5 t/ha', pericarp: '-', notes: 'Red kernel, popular for snacks' },
            { name: 'Walawa', type: 'Improved', duration: '110 days', yield: '2.5-3 t/ha', pericarp: '-', notes: 'Large bold kernel, good for confectionery' },
        ],
        soilRequirements: { pH: '5.5 - 7.0', type: 'Light sandy loam to sandy soil', drainage: 'Very well-drained, loose soil essential for peg penetration', preparation: 'Deep ploughing. Fine tilth. Apply gypsum at 200 kg/ha at flowering.' },
        waterRequirements: 'Rainfall 500-600mm during crop period. Critical water stages: flowering and pod formation. Moderate drought tolerance.',
        plantingGuide: { spacing: '30×15 cm', method: 'Direct seeding, one seed per hole', depth: '3-5 cm', seedRate: '100-120 kg/ha (in-shell)', bestMonths: { yala: 'April-May', maha: 'Not recommended in most areas' } },
        growthStages: [
            { stage: 'Emergence', duration: '0-14 days', care: 'Ensure seed treated with fungicide. Good soil moisture at planting.' },
            { stage: 'Vegetative', duration: '14-35 days', care: 'Weed control critical. Apply basal fertilizer.' },
            { stage: 'Flowering/Pegging', duration: '35-70 days', care: 'Apply gypsum. Do not disturb soil around plants. Earth up lightly.' },
            { stage: 'Pod Maturity', duration: '70-105 days', care: 'Reduce watering near maturity. Check pod maturity by sampling.' },
        ],
        harvestingTips: 'Harvest when inner shell shows darkened veins and kernels fill pods. Uproot entire plant. Dry pods in sun for 5-7 days to <8% moisture.',
        marketInfo: { peakDemand: 'Year-round, peak during festive seasons', avgPrice: 'Rs. 400-700/kg (shelled)', exportPotential: 'Moderate - processed groundnut products' },
    },
    {
        id: 'mungbean',
        name: 'Mung Bean',
        sinhalaName: 'මුං ඇට',
        tamilName: 'பச்சைப் பயறு',
        emoji: '🫘',
        zones: ['dry'],
        seasons: ['yala', 'maha'],
        overview: 'Mung bean is a short-duration pulse crop popular in the dry zone. Often grown as a rotation crop between rice seasons or in upland areas. Major production in Anuradhapura, Hambantota, and Monaragala.',
        economicImportance: 'Important protein source. Short duration allows fitting into cropping systems. Fixes nitrogen, improving soil fertility.',
        varieties: [
            { name: 'MI-5', type: 'Improved', duration: '65 days', yield: '1.2-1.5 t/ha', pericarp: '-', notes: 'Most popular, high yielding' },
            { name: 'MI-6', type: 'Improved', duration: '60 days', yield: '1.0-1.3 t/ha', pericarp: '-', notes: 'Extra short duration, good for rice-based systems' },
            { name: 'Ari', type: 'Improved', duration: '70 days', yield: '1.3-1.5 t/ha', pericarp: '-', notes: 'Large seed size, good market value' },
        ],
        soilRequirements: { pH: '6.0 - 7.5', type: 'Well-drained sandy loam', drainage: 'Good drainage, does not tolerate waterlogging', preparation: 'Minimum tillage possible. Plough once and harrow. Can follow rice with minimum preparation.' },
        waterRequirements: 'Needs 300-400mm. Moderate drought tolerance. Avoid excess water. Rain-fed cultivation is common.',
        plantingGuide: { spacing: '30×10 cm or broadcast', method: 'Direct seeding', depth: '2-3 cm', seedRate: '25-30 kg/ha (rows), 35-40 kg/ha (broadcast)', bestMonths: { yala: 'March-April', maha: 'September-October' } },
        growthStages: [
            { stage: 'Emergence', duration: '0-10 days', care: 'Ensure uniform emergence. Gap fill if needed.' },
            { stage: 'Vegetative', duration: '10-30 days', care: 'One weeding at 2-3 weeks. Apply fertilizer at sowing.' },
            { stage: 'Flowering/Pod Fill', duration: '30-55 days', care: 'Watch for pod borer and bean fly. Avoid disturbing plants during flowering.' },
            { stage: 'Maturity', duration: '55-65 days', care: 'Pods turn black/brown when mature. Harvest in 2-3 pickings as pods mature unevenly.' },
        ],
        harvestingTips: 'Harvest mature pods before they shatter (turn brown/black). Pick every 3-4 days. Sun-dry pods and thresh. Clean and store at <12% moisture.',
        marketInfo: { peakDemand: 'Year-round, used in curries and sprouts', avgPrice: 'Rs. 400-600/kg', exportPotential: 'Low - mainly domestic consumption' },
    },
    {
        id: 'cowpea',
        name: 'Cowpea',
        sinhalaName: 'කව්පි',
        tamilName: 'தட்டப்பயறு',
        emoji: '🌱',
        zones: ['dry', 'intermediate'],
        seasons: ['yala', 'maha'],
        overview: 'Cowpea is a drought-tolerant legume widely grown in dry zone home gardens and as a field crop. Valued for both grain and green pods (long beans). Important crop in Anuradhapura, Kurunegala, and Hambantota.',
        economicImportance: 'Important protein source for rural households. Excellent nitrogen-fixing ability improves soil. Dual-purpose: grain and vegetable.',
        varieties: [
            { name: 'Bombay', type: 'Bush', duration: '75 days', yield: '1.5-2 t/ha (grain)', pericarp: '-', notes: 'Most popular dry grain variety' },
            { name: 'Waruni', type: 'Bush', duration: '70 days', yield: '1.5 t/ha', pericarp: '-', notes: 'Good drought tolerance' },
            { name: 'MI-35', type: 'Bush', duration: '75 days', yield: '1.5-2 t/ha', pericarp: '-', notes: 'DOA improved variety' },
            { name: 'Gannoruwa Mee Karal', type: 'Trailing', duration: '65 days', yield: '8-10 t/ha (green pods)', pericarp: '-', notes: 'Long bean type for fresh vegetable market' },
        ],
        soilRequirements: { pH: '6.0 - 7.0', type: 'Sandy loam, grows in poor soils', drainage: 'Well-drained, tolerates drought', preparation: 'Minimum tillage. Plough and harrow once. Cowpea grows well in low-fertility soils.' },
        waterRequirements: 'Needs 300-500mm. Very drought tolerant once established. Avoid waterlogging.',
        plantingGuide: { spacing: '45×15 cm (bush) or 1m×50 cm (trailing)', method: 'Direct seeding', depth: '3-4 cm', seedRate: '20-30 kg/ha', bestMonths: { yala: 'April', maha: 'October' } },
        growthStages: [
            { stage: 'Emergence', duration: '0-10 days', care: 'Ensure adequate soil moisture. Seeds germinate in 4-6 days.' },
            { stage: 'Vegetative', duration: '10-35 days', care: 'One weeding required. Apply basal fertilizer only (low N needed as it fixes nitrogen).' },
            { stage: 'Flowering/Pod Fill', duration: '35-65 days', care: 'Watch for aphids and pod borer. Harvest green pods regularly for vegetable types.' },
        ],
        harvestingTips: 'For grain: harvest when pods turn brown and dry. For green pods: pick every 2-3 days when tender. Dry grain to <12% moisture content.',
        marketInfo: { peakDemand: 'Year-round', avgPrice: 'Rs. 300-500/kg (grain), Rs. 150-250/kg (green pods)', exportPotential: 'Low' },
    },
    {
        id: 'vegetables',
        name: 'Vegetables (Mixed)',
        sinhalaName: 'එළවළු',
        tamilName: 'காய்கறிகள்',
        emoji: '🥬',
        zones: ['wet', 'intermediate'],
        seasons: ['yala', 'maha'],
        overview: 'Up-country and mid-country vegetables include beans, tomato, carrot, cabbage, leeks, capsicum, and beetroot. Nuwara Eliya, Badulla, and Matale are major production areas. Low-country vegetables like brinjal, bitter gourd, snake gourd, and okra are grown in wet and intermediate zones.',
        economicImportance: 'Vital for nutritional security. Provides high income per unit area. Employment for thousands of smallholder farmers.',
        varieties: [
            { name: 'Beans (Wade)', type: 'OPV', duration: '55-60 days', yield: '12-15 t/ha', pericarp: '-', notes: 'Popular bush bean variety' },
            { name: 'Tomato (Thilina)', type: 'Hybrid', duration: '75-80 days', yield: '40-50 t/ha', pericarp: '-', notes: 'High yielding, bacterial wilt tolerant' },
            { name: 'Carrot (New Kuroda)', type: 'OPV', duration: '80-90 days', yield: '25-30 t/ha', pericarp: '-', notes: 'Best for up-country cultivation' },
            { name: 'Leeks (Local)', type: 'OPV', duration: '90-100 days', yield: '20-25 t/ha', pericarp: '-', notes: 'Major up-country vegetable' },
            { name: 'Cabbage (Green Coronet)', type: 'Hybrid', duration: '70-80 days', yield: '30-40 t/ha', pericarp: '-', notes: 'Popular for Nuwara Eliya and Bandarawela' },
        ],
        soilRequirements: { pH: '5.5 - 7.0', type: 'Loamy to sandy loam, rich in organic matter', drainage: 'Well-drained raised beds', preparation: 'Deep dig beds to 30cm. Add 20-30 t/ha compost. Prepare raised beds 1m wide with 30cm paths.' },
        waterRequirements: 'Regular irrigation essential. Drip or sprinkler recommended. Most vegetables need 500-800mm during crop period.',
        plantingGuide: { spacing: 'Varies by crop: 45×30cm (beans), 60×45cm (tomato), 30×10cm (carrot)', method: 'Transplanting (tomato, cabbage) or direct seeding (beans, carrot)', depth: '1-3 cm', seedRate: 'Varies by crop', bestMonths: { yala: 'March-April', maha: 'September-October' } },
        growthStages: [
            { stage: 'Establishment', duration: '0-21 days', care: 'Protect seedlings from pests. Maintain soil moisture. Apply shade for tender crops.' },
            { stage: 'Vegetative Growth', duration: '21-45 days', care: 'Regular weeding. Apply fertilizer at 2-week intervals. Staking for tomato and beans.' },
            { stage: 'Fruiting/Harvest', duration: '45-90 days', care: 'Harvest regularly to encourage more fruiting. Monitor for pests and diseases.' },
        ],
        harvestingTips: 'Harvest at proper maturity stage. Early morning harvest retains freshness. Grade, pack, and transport quickly to market.',
        marketInfo: { peakDemand: 'Variable - prices fluctuate seasonally', avgPrice: 'Rs. 100-500/kg depending on crop and season', exportPotential: 'Moderate for selected crops' },
    },
    {
        id: 'cashew',
        name: 'Cashew',
        sinhalaName: 'කජු',
        tamilName: 'முந்திரி',
        emoji: '🌰',
        zones: ['intermediate', 'dry'],
        seasons: ['yala'],
        overview: 'Cashew is grown in the dry and intermediate zones, particularly in Puttalam, Kurunegala, Hambantota, Batticaloa, and Northern Province districts. Requires dry weather during flowering for good nut set.',
        economicImportance: 'Cultivated on ~30,000 hectares. Growing export product. Sri Lankan cashew is renowned for taste and quality.',
        varieties: [
            { name: 'Anuradhapura Selection', type: 'Local', duration: '3 years to fruit', yield: '8-10 kg/tree', pericarp: '-', notes: 'Adapted to dry zone conditions' },
            { name: 'WRDC 3', type: 'Improved', duration: '2-3 years to fruit', yield: '12-15 kg/tree', pericarp: '-', notes: 'High yielding grafted variety' },
            { name: 'Colombo Selection', type: 'Local', duration: '3 years to fruit', yield: '6-8 kg/tree', pericarp: '-', notes: 'Well-adapted to intermediate zone' },
        ],
        soilRequirements: { pH: '5.0 - 6.5', type: 'Well-drained laterite, sandy loam', drainage: 'Good drainage, tolerates dry conditions', preparation: 'Clear land. Pit size 60×60×60cm. Fill with topsoil and compost 2 weeks before planting.' },
        waterRequirements: 'Rainfall 1000-2000mm. Drought tolerant but irrigation during first 2 years improves establishment. Dry period during flowering essential.',
        plantingGuide: { spacing: '8m × 8m', method: 'Grafted plants or air-layered plants for uniformity', depth: '60cm pits', seedRate: '156 plants/ha', bestMonths: { yala: 'May-June', maha: '' } },
        growthStages: [
            { stage: 'Establishment', duration: '0-3 years', care: 'Water during dry spells. Mulch around trees. Prune to shape. Intercrop with short-term crops.' },
            { stage: 'Bearing', duration: '3+ years', care: 'Apply fertilizer annually. Prune dead/crossing branches. Watch for tea mosquito bug.' },
        ],
        harvestingTips: 'Collect fallen nuts daily during Feb-Apr harvest season. Separate nuts from apple. Sun-dry nuts for 2-3 days. Store in jute bags in dry place.',
        marketInfo: { peakDemand: 'Year-round processed, raw nut season Feb-Apr', avgPrice: 'Rs. 1500-3000/kg (processed kernels)', exportPotential: 'High - growing global demand' },
    },
    {
        id: 'banana',
        name: 'Banana',
        sinhalaName: 'කෙසෙල්',
        tamilName: 'வாழை',
        emoji: '🍌',
        zones: ['wet', 'intermediate'],
        seasons: ['yala', 'maha'],
        overview: 'Banana is widely cultivated in home gardens and commercial plantations across wet and intermediate zones. Multiple varieties grown for dessert and cooking purposes. Major production in Ratnapura, Kandy, Kurunegala, and Matale districts.',
        economicImportance: 'Most widely consumed fruit in Sri Lanka. Important income source for smallholder farmers. Multiple value-added products (chips, flour).',
        varieties: [
            { name: 'Ambul (Mysore)', type: 'Dessert', duration: '10-12 months', yield: '20-25 t/ha', pericarp: '-', notes: 'Most popular dessert banana, slightly sour-sweet' },
            { name: 'Kolikuttu (Silk)', type: 'Dessert', duration: '12-14 months', yield: '25-30 t/ha', pericarp: '-', notes: 'Premium variety, highest market price' },
            { name: 'Anamalu (Cavendish)', type: 'Dessert', duration: '10-12 months', yield: '30-40 t/ha', pericarp: '-', notes: 'High yielding, export quality' },
            { name: 'Alu Kesel (Cooking)', type: 'Cooking', duration: '14-16 months', yield: '25-30 t/ha', pericarp: '-', notes: 'Used in curries and boiled (plantain type)' },
            { name: 'Seeni Kesel', type: 'Dessert', duration: '14-16 months', yield: '15-20 t/ha', pericarp: '-', notes: 'Small, very sweet, popular traditional variety' },
        ],
        soilRequirements: { pH: '5.5 - 7.0', type: 'Deep, fertile loamy soil rich in organic matter', drainage: 'Well-drained but moisture retentive', preparation: 'Dig pits 45×45×45cm. Fill with topsoil + 10kg compost + 200g dolomite per pit.' },
        waterRequirements: 'Need 1200-2200mm/year. Regular watering, especially during dry spells. Can tolerate some waterlogging but not prolonged stagnation.',
        plantingGuide: { spacing: '2m × 2m to 3m × 3m depending on variety', method: 'Sword suckers or tissue culture plants', depth: '45cm pits', seedRate: '1100-2500 plants/ha', bestMonths: { yala: 'April-May', maha: 'October' } },
        growthStages: [
            { stage: 'Establishment', duration: '0-3 months', care: 'Water regularly. Apply mulch around base. Remove weeds in 1.5m circle.' },
            { stage: 'Vegetative', duration: '3-7 months', care: 'Apply fertilizer monthly. Remove excess suckers (keep only 1 follower). Support tall plants.' },
            { stage: 'Flowering/Fruiting', duration: '7-12 months', care: 'Remove male bud after last hand opens. Cover bunch with blue polythene bag. Prop plant to prevent toppling.' },
        ],
        harvestingTips: 'Harvest when fingers are well-rounded and light green. Cut bunch carefully with sharp knife. Ripen in enclosed area with ethylene source (smoking or Ethrel).',
        marketInfo: { peakDemand: 'Year-round, prices peak during festive seasons (Sinhala New Year, Vesak)', avgPrice: 'Rs. 80-250/kg depending on variety', exportPotential: 'Moderate - Ambul and Kolikuttu have export potential' },
    },
];

// === HELPER FUNCTIONS ===

export const getCropById = (cropId) => {
    return CROP_RECOMMENDATIONS.find(crop => crop.id === cropId);
};

export const getCropsByZone = (zoneId) => {
    return CROP_RECOMMENDATIONS.filter(crop => crop.zones.includes(zoneId));
};

export const getRecommendedCrops = (zoneId, season) => {
    return CROP_RECOMMENDATIONS.filter(crop =>
        crop.zones.includes(zoneId) && crop.seasons.includes(season)
    );
};

export const searchCrops = (query) => {
    const q = query.toLowerCase();
    return CROP_RECOMMENDATIONS.filter(crop =>
        crop.name.toLowerCase().includes(q) ||
        crop.sinhalaName.includes(q) ||
        crop.tamilName.includes(q)
    );
};
